name: Build and Scan

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    - name: Build EXE
      run: |
        python -m PyInstaller --noupx --onefile --windowed --icon=python.ico --add-data "python.ico;." --add-data "python.png;." --name="PythonProjectMngr" app.py
      env:
        PYTHONIOENCODING: utf-8

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: PythonProjectMngr
        path: dist/PythonProjectMngr.exe

    - name: Scan with VirusTotal
      if: success() && secrets.VIRUSTOTAL_API_KEY != ''
      uses: crazy-max/ghaction-virustotal@v4.0.0
      with:
        vt_api_key: ${{ secrets.VIRUSTOTAL_API_KEY }}
        files: dist/PythonProjectMngr.exe
